global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'chm80076@gmail.com'
  smtp_auth_username: 'chm80076@gmail.com'
  smtp_auth_password: 'hxjk rmkh nubz dthx'
  smtp_require_tls: true

route:
  receiver: 'email-notifications'

receivers:
- name: 'email-notifications'
  email_configs:
  - to: 'dhanasekhar@middlewaretalents.com'
    send_resolved: true
