# apiVersion: v1
# kind: Service
# metadata:
#   name: frontend
# spec:
#   selector:
#     app: frontend
#   ports:
#     - port: 80
#       targetPort: 80
#   type: ClusterIP
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - port: 80        # Cluster IP port inside cluster
      targetPort: 80  # Pod port
      nodePort: 30080 # NodePort for external access
  type: NodePort
