# apiVersion: v1
# kind: Service
# metadata:
#   name: order-service
# spec:
#   type: ClusterIP        # Change from NodePort to ClusterIP
#   selector:
#     app: order-service
#   ports:
#     - protocol: TCP
#       port: 3002         # Internal cluster port
#       targetPort: 3002   # Container port in the pod

apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: default       # make sure this matches your Deployment namespace
  labels:
    app: order-service
spec:
  type: ClusterIP
  selector:
    app: order-service
  ports:
    - name: http          # <-- must match ServiceMonitor port
      protocol: TCP
      port: 3002          # Internal cluster port
      targetPort: 3002    # Container port in the pod
