# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: product-service
# spec:
#   selector:
#     app: product-service
#   ports:
#     - port: 3001
#       targetPort: 3001
#   type: ClusterIP
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product-service
  ports:
    - port: 3001        # Service port inside cluster
      targetPort: 3001  # Container port
      nodePort: 31001   # Fixed port on Minikube IP
  type: NodePort        # Change from ClusterIP to NodePort
