# apiVersion: v1
# kind: Service
# metadata:
#   name: product-service
# spec:
#   type: ClusterIP
#   selector:
#     app: product-service
#   ports:
#     - protocol: TCP
#       port: 3001        # Internal cluster port
#       targetPort: 3001  # Container port in the pod
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: default
  labels:
    app: product-service   # must match ServiceMonitor selector
spec:
  type: ClusterIP
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      name: http
