# apiVersion: v1
# kind: Service
# metadata:
#   name: user-service
# spec:
#   selector:
#     app: user-service
#   ports:
#     - port: 3003
#       targetPort: 3003
#   type: ClusterIP
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - port: 3003        # Service port inside the cluster
      targetPort: 3003  # Container port
      nodePort: 31003   # Fixed port on Minikube IP
  type: NodePort        # Change from ClusterIP to NodePort
